export type ICreateHopDongNs = {
  soHopDong?: string;
  idLoaiHopDong?: number;
  ngayKyKet?: Date;
  ngayBatDauThuViec?: Date;
  ngayKetThucThuViec?: Date;
  hopDongCoThoiHanTuNgay?: Date;
  hopDongCoThoiHanDenNgay?: Date;
  luongCoBan?: number;
  idToBoMon?: number;
  idPhongBan?: number;
  idChucVu?: number;
  ghiChu?: string;
  idNhanSu?: number;
  currency: string | null;
  payFrequency: string | null;
  maNhanSu?: string;
  maSoThue?: string;
  tenNganHang1?: string;
  atm1?: string;
  tenNganHang2?: string;
  atm2?: string;
};
