import { IQueryPaging } from '@models/common/model.common';
import { ICreateNsQuanHe, IViewNsQuanHe } from './quanHeGiaDinh.model';
import { IVIewNsQuaTrinhCongTac } from './quaTrinhCongTac.model';

export type IQueryNhanSu = IQueryPaging & {
  cccd?: string;
  idPhongBan?: number;
};

export type IViewNhanSu = {
  idNhanSu: number;
  maNhanSu?: string;
  hoDem?: string;
  ten?: string;
  hoTen?: string;
  ngaySinh?: Date | string;
  noiSinh?: string;
  gioiTinh?: number;
  quocTich?: number;
  danToc?: number;
  tonGiao?: number;
  nguyenQuan?: string;
  noiOHienTai?: string;
  soCccd?: string;
  ngayCapCccd?: Date | string;
  noiCapCccd?: string;
  soDienThoai?: string;
  email?: string;
  khanCapSoDienThoai?: string;
  khanCapNguoiLienHe?: string;
  tenChucVu: string;
  tenPhongBan: string;
  thongTinGiaDinh?: IViewNsQuanHe[];
  quaTrinhCongTac?: IVIewNsQuaTrinhCongTac[];
  chieuCao?: number;
  canNang?: number;
  nhomMau?: string;
  trinhDoHocVan?: string;
  trinhDoNgoaiNgu?: string;
  tenHocVi?: string;
  tenChuyenNganhHocVi?: string;
  tenHocHam?: string;
  tenChuyenNganhHocHam?: string;
  ngayVaoDang?: Date;
};

export type ICreateNhanSu = {
  hoDem?: string;
  ten?: string;
  ngaySinh?: Date;
  noiSinh?: string;
  gioiTinh?: number;
  quocTich?: number;
  danToc?: number;
  tonGiao?: number;
  nguyenQuan?: string;
  noiOHienTai?: string;
  soCccd?: string;
  ngayCapCccd?: Date;
  noiCapCccd?: string;
  soDienThoai?: string;
  email?: string;
  khanCapSoDienThoai?: string;
  khanCapNguoiLienHe?: string;
  thongTinGiaDinh?: ICreateNsQuanHe[];
  chieuCao?: number;
  canNang?: number;
  nhomMau?: string;
  trinhDoHocVan?: string;
  trinhDoNgoaiNgu?: string;
  tenHocVi?: string;
  tenChuyenNganhHocVi?: string;
  tenHocHam?: string;
  tenChuyenNganhHocHam?: string;
  ngayVaoDang?: Date;
};

export type IUpdateNhanSu = {
  idNhanSu: number;
  hoDem?: string;
  ten?: string;
  ngaySinh?: Date;
  noiSinh?: string;
  gioiTinh?: number;
  quocTich?: number;
  danToc?: number;
  tonGiao?: number;
  nguyenQuan?: string;
  noiOHienTai?: string;
  soCccd?: string;
  ngayCapCccd?: Date;
  noiCapCccd?: string;
  soDienThoai?: string;
  email?: string;
  khanCapSoDienThoai?: string;
  khanCapNguoiLienHe?: string;
  thongTinGiaDinh?: ICreateNsQuanHe[];
  chieuCao?: number;
  canNang?: number;
  nhomMau?: string;
  trinhDoHocVan?: string;
  trinhDoNgoaiNgu?: string;
  tenHocVi?: string;
  tenChuyenNganhHocVi?: string;
  tenHocHam?: string;
  tenChuyenNganhHocHam?: string;
  ngayVaoDang?: Date;
};

export type IViewThongKeNsTheoPhongBan = {
  id: number;
  stt?: number | null;
  tenPhongBan: string | null;
  soLuongNhanSu: number;
};
