import type { Metadata } from "next";
import localFont from "next/font/local";
import { Suspense } from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import LayoutState from "@components/layout/LayoutState";
import Loading from "@components/common/Loading";
import StoreProvider from "./StoreProvider";
import "@src/styles/globals.scss";

const geistSans = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Digital University",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AntdRegistry>
            <Suspense fallback={<Loading />}>
              <LayoutState>{children}</LayoutState>
            </Suspense>
          </AntdRegistry>
        </body>
      </html>
    </StoreProvider>
  );
}
