// <auto-generated />
using System;
using D.Core.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace D.Core.Domain.Migrations
{
    [DbContext(typeof(CoreDBContext))]
    [Migration("20250910112559_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("D.Core.Domain.Hrm.NhanSu.NsNhanSu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Atm1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Atm2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("DaChamDutHopDong")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaVeHuu")
                        .HasColumnType("bit");

                    b.Property<int?>("DanToc")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<int?>("HienTaiChucVu")
                        .HasColumnType("int");

                    b.Property<int?>("HienTaiPhongBan")
                        .HasColumnType("int");

                    b.Property<string>("HoDem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdHopDong")
                        .HasColumnType("int");

                    b.Property<int?>("IdLoaiHopDong")
                        .HasColumnType("int");

                    b.Property<bool?>("IsThoiViec")
                        .HasColumnType("bit");

                    b.Property<string>("KhanCapNguoiLienHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhanCapSoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanSu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapCccd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguyenQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCapCccd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiOHienTai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiSinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuocTich")
                        .HasColumnType("int");

                    b.Property<string>("SoCccd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHang1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHang2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TonGiao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NsNhanSu", "hrm");
                });
#pragma warning restore 612, 618
        }
    }
}
